FROM node:lts-alpine3.14 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
# RUN npm run build

# FROM nginx:1.12
# COPY --from=build-stage /app/build /usr/share/nginx/html
# EXPOSE 80
# ENTRYPOINT [ "nginx", "-g", "daemon off;" ]

EXPOSE 3000
ENTRYPOINT ["HTTPS=true", "npm", "run", "start" ]