version: "3.8"

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - frontend
      - backend
      - db
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ../cert:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
  frontend:
    depends_on:
      - backend
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    restart: unless-stopped
  backend:
    depends_on:
      - db
    build: ./server
    command: ./docker-entrypoint.prod.sh
    ports:
      - 3001:3001
    restart: unless-stopped
  db:
    image: postgres:alpine3.14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
